In [12]:
import pandas as pd
import numpy as np

In [13]:
df = pd.read_excel('20250506T142056.181-grdDemSaldo.xlsx', "grdDemSaldo", skiprows=1, names=["Cód. Estruturado", "Cód. Alternativo", "Cód. Insumo", "Descrição", "Unid.", "Quant Saldo", "Valor Saldo", "Quant Previsto", "Valor Previsto", "Quant Solicitação", "Valor Solicitação", "Quant Pedido", "Valor Pedido", "Quant Contrato", "Valor Contrato", "Quant Estoque Reservado", "Valor Estoque Reservado", "Quant Realizado", "Valor Realizado", "Cód. Alternativo", "Descrição Serviço 2º Nível" ] )
df

,Cód. Estruturado,Cód. Alternativo,Cód. Insumo,Descrição,Unid.,Quant Saldo,Valor Saldo,Quant Previsto,Valor Previsto,Quant Solicitação,...,Quant Pedido,Valor Pedido,Quant Contrato,Valor Contrato,Quant Estoque Reservado,Valor Estoque Reservado,Quant Realizado,Valor Realizado,Cód. Alternativo.1,Descrição Serviço 2º Nível
0,01,NaN,NaN,SERVIÇOS INICIAIS E COMPARTILHADOS,NaN,NaN,-1.437589e+06,NaN,3.887665e+06,NaN,...,NaN,97173.71,NaN,1123210.34,NaN,0,NaN,679303.765,NaN,NaN
1,01.01,NaN,NaN,SERVIÇOS TÉCNICOS,NaN,NaN,-3.113758e+05,NaN,4.244987e+05,NaN,...,NaN,26750.30,NaN,81178.21,NaN,0,NaN,203447.280,NaN,NaN
2,01.01.01,NaN,NaN,PROJETOS,NaN,NaN,-2.087907e+05,NaN,2.484987e+05,NaN,...,NaN,0.00,NaN,81178.21,NaN,0,NaN,127612.470,NaN,NaN
3,01.01.01.023,01.01.01.023,NaN,Coordenação e compatibilização de projetos,M2,NaN,7.500000e-03,16690.8906,2.002907e+05,NaN,...,NaN,0.00,NaN,0.00,NaN,0,NaN,0.000,NaN,NaN
4,01.01.01.023,NaN,19496.0,SERVIÇO DE COORDENAÇÃO DE PROJETOS,UN,0.0006,7.500000e-03,16690.8906,2.002907e+05,16690.89,...,0.0,0.00,0.0,0.00,0.0,0,0.0,0.000,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2178,12.01,NaN,NaN,Taxa de Obra,NaN,NaN,0.000000e+00,NaN,0.000000e+00,NaN,...,NaN,0.00,NaN,0.00,NaN,0,NaN,0.000,NaN,NaN
2179,12.01.01,NaN,NaN,Taxa de obra,NaN,NaN,0.000000e+00,NaN,0.000000e+00,NaN,...,NaN,0.00,NaN,0.00,NaN,0,NaN,0.000,NaN,NaN
2180,12.01.01.001,01.01.01.024,NaN,Manual de obra,VB,0.0000,0.000000e+00,0.0000,0.000000e+00,NaN,...,NaN,0.00,NaN,0.00,NaN,0,NaN,0.000,NaN,NaN
2181,12.01.01.001,NaN,19458.0,SERVIÇO TAXA DE ADM OBRA,UN,0.0000,0.000000e+00,0.0000,0.000000e+00,0.00,...,0.0,0.00,0.0,0.00,0.0,0,0.0,0.000,NaN,NaN
2182,NaN,NaN,NaN,NaN,NaN,NaN,3.176866e+07,NaN,7.391672e+07,NaN,...,NaN,359751.12,NaN,12895403.26,NaN,0,NaN,6780755.395,NaN,NaN

In [14]:
df['Valor unit Saldo'] = np.where(
df['Quant Saldo'].isnull(),
df['Valor Saldo'],
(df['Valor Saldo']/df['Quant Saldo'])
)

In [15]:
df['Valor unit Previsto'] = np.where(
df['Quant Previsto'].isnull(),
df['Valor Previsto'],
(df['Valor Previsto']/df['Quant Previsto'])
)

In [16]:
condicoes = [
        df['Cód. Insumo'].isnull(),
        df['Quant Saldo'] < 0,
        df['Quant Saldo'].isnull() & (df['Valor unit Saldo'] < 0),
        df['Quant Saldo'].isnull() & (df['Valor unit Saldo'] >= 0),
        df['Valor unit Saldo'] < df['Valor unit Previsto'],
    ]
valores = [2,0,0, 1, 0]
default = 1
df['sit orcamento'] = np.select(condicoes, valores, default=default)

In [17]:
soma = df.loc[df.index[-1], ['Valor Saldo', 'Valor Previsto',
                             'Valor Solicitação', 'Valor Pedido',
                             'Valor Contrato', 'Valor Estoque Reservado',
                             'Valor Realizado']]
soma

Valor Saldo                31768661.784606
Valor Previsto             73916717.480648
Valor Solicitação          22112145.921043
Valor Pedido                     359751.12
Valor Contrato                 12895403.26
Valor Estoque Reservado                  0
Valor Realizado                6780755.395
Name: 2182, dtype: object